CREATE TABLE bears (
    id INTEGER PRIMARY KEY,
    name VARCHAR(255) NULL,
    age INTEGER NOT NULL,
    sex VARCHAR(1) NOT NULL,
    color VARCHAR(255) NOT NULL,
    temperament VARCHAR(255) NOT NULL,
    alive BOOLEAN NOT NULL
);

